# Generated by Django 3.0.1 on 2019-12-28 22:37

#para generar los primeros datos
from django.db import migrations
from django.contrib.auth.hashers import make_password #para encriptar contraseña


def createPropuestasEstatus(app, schema_editor):
    PropuestasEstatus = app.get_model('gestorAppTG', 'PropuestasEstatus')
    PropuestasEstatus.objects.create(nombre='Por evaluar')
    PropuestasEstatus.objects.create(nombre='Diferida')
    PropuestasEstatus.objects.create(nombre='Aprobada')
    PropuestasEstatus.objects.create(nombre='Rechazada')

def createTesisEstatus(app, schema_editor):
    TesisEstatus = app.get_model('gestorAppTG', 'TesisEstatus')
    TesisEstatus.objects.create(nombre='Por entregar')
    TesisEstatus.objects.create(nombre='Entregado y pendiente por defender')
    TesisEstatus.objects.create(nombre='Diferido')
    TesisEstatus.objects.create(nombre='Aprobado')
    TesisEstatus.objects.create(nombre='Aprobado con solicitud de correcciones')
    TesisEstatus.objects.create(nombre='Rechazado')


def createTermin(app, schema_editor):
    Termin = app.get_model('gestorAppTG','Termin')
    Termin.objects.create(id="201915", descripcion='primer semestre del año académico')
    Termin.objects.create(id="201925", descripcion='segundo semestre del año académico')


def createUsers(app, schema_editor):
    User = app.get_model('gestorAppTG','User')
    User.objects.create(
        username="admin",
        password=make_password("admin123"),
        esAdmin=True
    )
    User.objects.create(
        username="Manager",
        password=make_password("manager123"),
        esManager=True
    )
    User.objects.create(
    	username="invitado",
        password=make_password("invitado123"),
        esInvitado=True
    )
   
class Migration(migrations.Migration):

    dependencies = [
        ('gestorAppTG', '0001_primera_migracion'),
    ]

    operations = [
        migrations.RunPython(createPropuestasEstatus),
        migrations.RunPython(createTesisEstatus),
        migrations.RunPython(createTermin),
        migrations.RunPython(createUsers)
    ]
